/-
This file provides decidable verification for SemanticWorkflowGraph. It extends the existing predicate systems with a concret layer
that enables we use `native_decid` to prove the semantic soundness
-/
import AgentVerifier.StaticSemanticLayer.StaticSemanticVariable.PredicateType
import AgentVerifier.StaticSemanticLayer.StaticSemanticVariable.PredicateType_DecidableEq
import AgentVerifier.StaticSemanticLayer.StaticSemanticVariable.PredicateType_utils
import AgentVerifier.StaticSemanticLayer.StaticSemanticVariable.ExtensiblePredicate
import AgentVerifier.StaticSemanticLayer.StaticSemanticVariable.CompatibleCheck
import AgentVerifier.StaticSemanticLayer.StaticSemanticVariable.example_userDefinedPredicate_DictAllValuesPredicate
